services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://admin:secret@mongo_db:27017/oz-tech-test?authSource=admin
    depends_on:
      - mongo_db
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  mongo_db:
    image: docker.io/library/mongo
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_ROOT_USERNAME=admin
    ports:
      - '27017:27017'
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
